CREATE OR REPLACE PROCEDURE SAMPLE_DATA_PROC(ID INT)
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
        CUR_QUERY CURSOR FOR SELECT QUERY FROM WRAP_TABLE ORDER BY NO;   //Here we must create WRAP_TABLE with appropriate data
        EQUERY STRING;

BEGIN
        OPEN CUR_QUERY;
    LOOP
        FETCH CUR_QUERY INTO EQUERY;
            IF (EQUERY IS NULL) THEN
            BREAK;
            ELSE 
            EXECUTE IMMEDIATE EQUERY;
            END IF;
        END LOOP;
        CLOSE CUR_QUERY;
RETURN 'RELOADED DATA INTO TABLES';
END;
    
CALL SAMPLE_DATA_PROC(400);
